### ISSUE TITLE
Build keretrendszer beüzemelése

### ISSUE THREAD

**Issue by mnoncsi** [BME-MIT-IET/Projlab-plusz-plusz-iet-2018#1]
Maven

**Comment by mnoncsi** [comment]
@emesepadanyi Build keretrendszer beüzemelése.

**Comment by mnoncsi** [comment]
@Petofi95 Review-old légyszíves!

**Comment by Petofi95** [comment]
A keretrendszert beüzemeltük, a wiki elkészült.
