### ISSUE TITLE
Függőségek leválasztása a tesztekben

### ISSUE THREAD

**Issue by Petofi95** [BME-MIT-IET/Projlab-plusz-plusz-iet-2018#10]
@emesepadanyi [javaslatára ](https://github.com/BME-MIT-IET/Projlab-plusz-plusz-iet-2018/issues/7#issuecomment-390526642) válasszuk le a fájlba írási/olvasási függőségeket a tesztekben, hogy azok önállóan is működőképesek legyenek és ne lassítsa őket a fájl írás/olvasás.

A #7 issue-t lezártam.

**Comment by Petofi95** [comment]
@emesepadanyi javította c2b15b8 commitban. 
A #11 pull requestet reviewoltam és mergeltem. A branchet töröltem.

**Comment by caspien6** [comment]
Review-oltam a kijavított teszteket.
