### ISSUE TITLE
Statikus ellenőrzés a find bugs-zal

### ISSUE THREAD

**Issue by emesepadanyi** [BME-MIT-IET/Projlab-plusz-plusz-iet-2018#12]
ellenőrzés, néhány jelentősségteljes bug átnézése, esetleg javítása, és wiki megírása

**Comment by Petofi95** [comment]
A wikiből még hiányoznak a képek.

**Comment by mnoncsi** [comment]
bc836a8c10c5278c7420a3e195dd63460ee24616

**Comment by mnoncsi** [comment]
beraktam a képeket

**Comment by caspien6** [comment]
Review-oltam, jók lettek a képek!
