### ISSUE TITLE
Projekt hozzáadása a repository-hoz

### ISSUE THREAD

**Issue by mnoncsi** [BME-MIT-IET/Projlab-plusz-plusz-iet-2018#2]
@emesepadanyi 
![](https://confluence.atlassian.com/bitbucket/files/304578655/633471987/2/1438357595788/git-training-remote-repositories-1.png)

**Comment by emesepadanyi** [comment]
kész.
https://github.com/BME-MIT-IET/Projlab-plusz-plusz-iet-2018/commit/4aba52d1b2c57e669fe71f238881dce2c4cc2820
@Petofi95 pls review.

**Comment by Petofi95** [comment]
Rendben. 
Legkozelebb kerlek egy masik branchen fejlessz, es kerj pull requestet a modositashoz.
