### ISSUE TITLE
JUnit teszt írás

### ISSUE THREAD

**Issue by caspien6** [BME-MIT-IET/Projlab-plusz-plusz-iet-2018#7]
Kód lefedettség növelése, új funkciók tesztelése.

**Comment by Petofi95** [comment]
Milyen eddig nem tesztelt funkcióhoz készült unit test? 
Majd az aktuális commitot kérlek linkeld be, hogy reviewolhassam és lezárhassam az issue-t.

**Comment by mnoncsi** [comment]
segítek megírni a wikit

**Comment by Petofi95** [comment]
Rendben. 
@caspien6, majd linkeld be az ide vonatkozó commitot/commitokat, kérlek.

**Comment by mnoncsi** [comment]
@caspien6 kicsit kiegészítettem

**Comment by caspien6** [comment]
Ez a commit lesz a megoldás 78068d257278da4a39b9502b65f3eb1bad799b1a .
Sajnos elfelejtettem külön branch-re rakni, mielőtt elkezdtem volna vele dolgozni :/

**Comment by Petofi95** [comment]
Igen.. nem gond.
Volt egy kis progress már a unit_testes branchen is korábbról, azt most mergeltük. 

Majd a wikire esetleg nézz rá, hogy ki lehet-e egészíteni valamivel.

**Comment by caspien6** [comment]
Okés, egy pár dolgot átírtam a wiki-n, de amúgy szerintem kész.

**Comment by Petofi95** [comment]
Köszi, jó lesz így szerintem.

**Comment by caspien6** [comment]
Szeretnék review-t kérni! @emesepadanyi  @Petofi95

**Comment by emesepadanyi** [comment]
Még lennének leválasztható függőségek a tesztekben, pl. fájlba írás és olvasás, de mivel az eredeti tesztek sem választották le ezeket, így vagy azokat is ki kéne javítani, vagy ezek is jók lesznek így.
Két okból is rossz, hogyha nincs leválasztva a könyvtár: bármikor kitörölheti valaki a teszteléshez szükséges fileokat, és akkor nem fognak tovább műköni a tesztek, vagy ha rengeteg ilyen típusú teszt lenne, akkor nagyon sokáig tartana, amíg lefutnak a tesztek, mert az külön idő, hogy megnyitogatja ezeket a fájlokat.
A tesztnek nem különösebb része, hogy valóban megnyitja-e a fájlokat, hanem csak a benne lévő adatból dolgozik a teszt, ezért, és a fentebb említett okok miatt szerintem le kéne választani a tesztekből a fájlból és fájlba írogatást.

Illetve sem az eredeti tesztekben, sem az általunk írt tesztekben nincsenek assert-ek. Csak arra vagyunk kíváncsiak, hogy lefut valami kód error nélkül, és a kimenet, vagy állapot változások nem érdekesek?

PS:
Elkezdtem utána nézni, hogy az input streamet hogyan lehetne valamilyen barátságos módon leválasztani filebeolvasásról. Mockolás nélküli legkönnyebb út:
String str = "my xml";
XSD2OWLMapper mapping = new XSD2OWLMapper(new ByteArrayInputStream(str.getBytes("UTF-8")));

**Comment by emesepadanyi** [comment]
Wiki-review:
A tesztek írásának nem az a célja, hogy több sor kódot lefedjenek, hanem hogy több sor kódról megbizonyosodjunk, hogy megfelelően működik-e. A nagy lefedettség még nem jelent jól letesztelt kódot.

**Comment by Petofi95** [comment]
Folytatás itt: #10
